// Code generated by protoc-gen-go. DO NOT EDIT.
// source: product.proto

/*
Package product is a generated protocol buffer package.

It is generated from these files:
	product.proto

It has these top-level messages:
	Supplier
	Product
*/
package product

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Supplier struct {
	SupplierId string `protobuf:"bytes,1,opt,name=supplier_id,json=supplierId" json:"supplier_id,omitempty"`
}

func (m *Supplier) Reset()                    { *m = Supplier{} }
func (m *Supplier) String() string            { return proto.CompactTextString(m) }
func (*Supplier) ProtoMessage()               {}
func (*Supplier) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Supplier) GetSupplierId() string {
	if m != nil {
		return m.SupplierId
	}
	return ""
}

type Product struct {
	ProductId   string `protobuf:"bytes,1,opt,name=product_id,json=productId" json:"product_id,omitempty"`
	ProductName string `protobuf:"bytes,2,opt,name=product_name,json=productName" json:"product_name,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Product) GetProductId() string {
	if m != nil {
		return m.ProductId
	}
	return ""
}

func (m *Product) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

func init() {
	proto.RegisterType((*Supplier)(nil), "Supplier")
	proto.RegisterType((*Product)(nil), "Product")
}

func init() { proto.RegisterFile("product.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 159 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x28, 0xca, 0x4f,
	0x29, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xd2, 0xe6, 0xe2, 0x08, 0x2e, 0x2d,
	0x28, 0xc8, 0xc9, 0x4c, 0x2d, 0x12, 0x92, 0xe7, 0xe2, 0x2e, 0x86, 0xb2, 0xe3, 0x33, 0x53, 0x24,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xb8, 0x60, 0x42, 0x9e, 0x29, 0x4a, 0xde, 0x5c, 0xec, 0x01,
	0x10, 0xdd, 0x42, 0xb2, 0x5c, 0x5c, 0x50, 0x83, 0x10, 0x4a, 0x39, 0xa1, 0x22, 0x9e, 0x29, 0x42,
	0x8a, 0x5c, 0x3c, 0x30, 0xe9, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26, 0xb0, 0x02, 0x6e, 0xa8, 0x98,
	0x5f, 0x62, 0x6e, 0xaa, 0x51, 0x24, 0x17, 0x57, 0x70, 0x72, 0x2e, 0xcc, 0x3c, 0x65, 0x2e, 0x2e,
	0xf7, 0xd4, 0x12, 0x18, 0x8f, 0x53, 0x0f, 0xe6, 0x28, 0x29, 0x0e, 0x3d, 0xa8, 0xa0, 0x12, 0x83,
	0x90, 0x1a, 0x17, 0xaf, 0x7b, 0x6a, 0x89, 0x63, 0x4e, 0x0e, 0x7e, 0x75, 0x49, 0x6c, 0x60, 0xbf,
	0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xda, 0x5b, 0xeb, 0x91, 0xec, 0x00, 0x00, 0x00,
}
